import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Job Board T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <video
          src="/assets/work.mp4"
          muted
          autoPlay
          className="h-screen w-screen object-cover  grayscale"
        />
        <div className="fixed top-1/2 left-1/2 flex -translate-x-1/2 -translate-y-1/2 transform flex-col justify-center gap-6">
          <Link href={"/employee"}>
            <button className="w-96 rounded-lg bg-white py-6 px-2 text-xl font-semibold hover:opacity-70">
              Looking for your next career?
            </button>
          </Link>
          <Link href="/employer">
            <button className="w-96 rounded-lg bg-white py-6 px-2 text-xl font-semibold hover:opacity-70">
              Looking for you next great employee?
            </button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
